library(caret)
set.seed(50)
split=createDataPartition(biopsy$class,p=.7,list=FALSE,times=1)
train=biopsy[split,]
test=biopsy[-split,]
model=glm(class~V1+V2+V3,data=train,family='binomial')
head(test)
test$predicted=predict(model,newdata=test,type='response')
predicted_labels=ifelse(test$predicted>0.5,'malignant','benign')
print(predicted_labels)
predicted_labels=factor(predicted_labels,levels=c('benign','malignant'))
print(predicted_labels)
cm=(confusionMatrix(test$class,predicted_labels))$table
print(cm)
